### ISSUE TITLE
Unable to use RFE wrapper method

### ISSUE THREAD

**Issue by ElsaClaude** [CPerscheid/Comprior#1]
Hi,

thanks a lot for such a wonderful tool ! I'm currently testing it in order to potentially benchmark a tool, and so far it's applying all that I am looking for.
I just have an issue when I want to test wrapper feature selection method and especially RFE ones.
In the config file when I write this line : 
`traditional_methods = Random ANOVA InfoGain ReliefF VB-FS SVMpRFE RandomForest Lasso`
It is working perfectly, even the SVMpRFE.

But if I add a NB-RFE for example : 
`traditional_methods = Random ANOVA InfoGain ReliefF VB-FS SVMpRFE RandomForest Lasso NB-RFE`
The pipeline crash with the following error : 

> 2023-08-14 11:23:40,698 Welcome to Comprior!
> 2023-08-14 11:23:40,699 ######################## PREPROCESS DATA... ########################
> 2023-08-14 11:23:46,154 ######################## ... FINISHED ########################
> 2023-08-14 11:23:46,155 ######################## EVALUATE INPUT DATA... ########################
> 2023-08-14 11:23:47,517 ######################## ... FINISHED ########################
> 2023-08-14 11:23:47,556 ######################## EVALUATE KNOWLEDGE BASES... ########################
> 2023-08-14 11:23:47,557 ######################## ...FINISHED ########################
> 2023-08-14 11:23:47,557 ######################## SELECT FEATURES... ########################
> 2023-08-14 11:23:47,558 ######################## Random... ########################
> 2023-08-14 11:23:47,561 ######################## Random finished ########################
> 2023-08-14 11:23:47,562 ######################## ANOVA... ########################
> 2023-08-14 11:23:47,739 ######################## ANOVA finished ########################
> 2023-08-14 11:23:47,740 ######################## InfoGain... ########################
> 2023-08-14 11:23:48,570 ######################## InfoGain finished ########################
> 2023-08-14 11:23:48,571 ######################## ReliefF... ########################
> 2023-08-14 11:23:49,520 ######################## ReliefF finished ########################
> 2023-08-14 11:23:49,521 ######################## VB-FS... ########################
> 2023-08-14 11:23:49,536 ######################## VB-FS finished ########################
> 2023-08-14 11:23:49,537 ######################## SVMpRFE... ########################
> 2023-08-14 11:23:52,269 ######################## SVMpRFE finished ########################
> 2023-08-14 11:23:52,270 ######################## RandomForest... ########################
> 2023-08-14 11:23:52,634 ######################## RandomForest finished ########################
> 2023-08-14 11:23:52,635 ######################## Lasso... ########################
> 2023-08-14 11:23:52,805 ######################## Lasso finished ########################
> Traceback (most recent call last):
>   File "pipeline.py", line 477, in <module>
>     pipeline.executePipeline()
>   File "pipeline.py", line 457, in executePipeline
>     outputDir = self.selectFeatures(datasetLocation)
>   File "pipeline.py", line 163, in selectFeatures
>     selector = selectorFactory.createFeatureSelector(methods[len(methods) - i])
>   File "/home/eclaude/Documents/These/EC_thesis_useful_scripts/Compare_FS_algo/Comprior/code/Python/comprior/featureselection.py", line 53, in createFeatureSelector
>     return self.createTraditionalSelector(name)
>   File "/home/eclaude/Documents/These/EC_thesis_useful_scripts/Compare_FS_algo/Comprior/code/Python/comprior/featureselection.py", line 95, in createTraditionalSelector
>     return WrapperSelector(selectorName)
>   File "/home/eclaude/Documents/These/EC_thesis_useful_scripts/Compare_FS_algo/Comprior/code/Python/comprior/featureselection.py", line 1213, in __init__
>     self.selector = self.createSelector()
>   File "/home/eclaude/Documents/These/EC_thesis_useful_scripts/Compare_FS_algo/Comprior/code/Python/comprior/featureselection.py", line 1257, in createSelector
>     selector = RFE(self.classifier, int(k))
> TypeError: __init__() takes 2 positional arguments but 3 were given

I ahve installed Comprior from source but I also have the issue when building the comprior image and running into it.

From my understanding, it might come from a scikit-learn RFE function that has been updated by the package but not in the Comprior pipeline maybe ?
I tried various versions of scikit-learn but was not able to fix the problem.

Do you have any idea how I could test X-RFE feature selection method through Comprior ?

Thanks again for developing Comprior, it is really useful !
Have a nice day,

Elsa Claude

**Comment by CPerscheid** [comment]
Hi Elsa, 
happy to see that the tool is useful for you. :) 

I just had a look at the code - the code snippet that is breaking is this:
```
k = utils.getConfigValue("Gene Selection - General", "selectKgenes")
selectorType = self.name.split("-")[1]
if selectorType == "RFE":
      selector = RFE(self.classifier, int(k))
```
According to the error, it says the init() function gets 3 arguments instead of 2 expected - so something seems to be wrong with either `self.classifier` or `int(k)`. Can you check what you put in your config file for "selectKgenes"? My suspicion is that it falsely parses this parameter and ends up with multiple values. Otherwise, you could also try to explicitly set RFE's `n_features_to_select` param, i.e. adapt the code to look like this (maybe it just does not recognize this parameter anymore correctly):
`selector = RFE(self.classifier, n_features_to_select=int(k))`

If you execute Comprior from the Python script (and not Docker), you can actually adapt the code as you like and add e.g. print statements (i.e., `print(k)`so see the value of variable k) anywhere to check if the values are correct. If you run it from a Docker container, you would have to rebuild the Container each time you changed something in the code...

One remark regarding the use of scikit-learn's RFE, though: I tried to use it in my own experiments, but found it not to be feasible at all - it just took days to finish (or I just stopped after like 7 days of execution, I don't remember exactly).

Hope this helps,

Cindy

**Comment by ElsaClaude** [comment]
Hi,

Thanks for the answer.
In the config file I have set "selectKgenes =50".
It seems that "selector = RFE(self.classifier, n_features_to_select=int(k))" is working. I was so sure that I already tried naming the parameters, ups, my bad.

Thanks for the warning about the RFE computation time. Apparently, LR-RFE might work on my data but as you said, it's taking a long time. Hope it won't be 1 week ahah.

Have a nice day,

Elsa

**Comment by CPerscheid** [comment]
Glad to hear it works. I will update the code accordingly once I have time. :) 

Best,

Cindy
